### ISSUE TITLE
Investigate & Upgrade Supported Node Version

### ISSUE THREAD

**Issue by finn-orsini** [wayfair/git-parse#21]
### Description

The node version specified in the README is overly permissive and allows for an unsupported version of node, [node 8](https://github.com/wayfair/git-parse#prerequisites).

### Suggested Fix

- Test package when using node LTS (14.x)
- Add [`engines`](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines) config to alert users of change
- Update README to reflect change

**Comment by Cooperbuilt** [comment]
Leaving a note here - reminder to upgrade node versions in our GH Actions (currently [semi-pinned to 10](https://github.com/wayfair/git-parse/blob/ee82e95b27844664d9ee1e9179d17d82804af069/.github/workflows/pr-checks.yml#L13))

**Comment by Cooperbuilt** [comment]
Closed by #49
