### ISSUE TITLE
HOT TAKE ALERT: Should we remove/replace Flow?

### ISSUE THREAD

**Issue by Cooperbuilt** [wayfair/git-parse#45]
❗ Disclaimer - this is meant to illicit some conversation. Please weigh in with your thoughts!

## Question
This repository uses Flow types to type check javascript. While Flow is a perfectly fine type checking system, there are some drawbacks. First, [flow-bin](https://github.com/wayfair/git-parse/blob/main/package.json#L52) is losing steam and Typrescript continues to gain widespread support. 

![stats_per_year_image](https://user-images.githubusercontent.com/15932239/137328599-e07e345a-df42-4bb4-b100-7873e8bd8e4e.png)

While this isn't inherently a bad thing, I think we should consider how it may impact the ease-to-contribution for our repo here. 

Also, Flow doesn't have a clear and public roadmap (note, we still haven't seen a v1). For comparisons sake, [Typescript does have a clear roadmap](https://github.com/Microsoft/TypeScript/wiki/Roadmap) and a stable v1

## Context
Given the focused nature of this package, I'm of the mind we should keep it as simple and easy to contribute to as possible. I don't personally see the benefit of Flow for avoiding type-related bugs and it could deter future contributor-ship given it's lack of widespread adoption. 

## Comments
I think we should remove flow. If someone has a strong opinion on type checking, we could convert to TS. Looking for thoughts!

**Comment by finn-orsini** [comment]
Closing, decision to adopt TS documented in https://github.com/wayfair/git-parse/issues/56, changes made in  https://github.com/wayfair/git-parse/pull/57
