### ISSUE TITLE
❓Should We Automate Changelog and Package Version Changes?

### ISSUE THREAD

**Issue by Cooperbuilt** [wayfair/git-parse#52]
## Question
Manually upgrading the package.json version and adding a changelog entry are possible automation / validation targets. One example of this would be semantic commits powering automatic changelog updates and a required version bump / changelog check for PRs to be merged. Does anyone have strong thoughts / opinions on if we should do this and if so, what it would look like?

## Context

We recently had a PR that made a major version change and didn't include a package json update, and also had a pr that didn't include a changelog update. These seem like good DX opportunities to automate away the need to think about this and in doing so, potentially increase the quality of the repo.

**Comment by GaryPWhite** [comment]
im sure there's an easy way to do this -- I'm gonna slap a "help wanted" on and hope we run into a knowledgeable person. If you're reading this and might know something feel free to join the conversation / open a PR!

**Comment by kv979w** [comment]
I would recommend using https://github.com/semantic-release/semantic-release.

**Comment by finn-orsini** [comment]
> One example of this would be semantic commits powering automatic changelog updates and a required version bump / changelog check for PRs to be merged. 

I agree with adding a CI step to enforce that the changelog has been updated (by adding to the [unreleased](https://github.com/wayfair/git-parse/blob/main/CHANGELOG.md#unreleased) section), but publishing a new release for every change results in unecessary churn for our consumers. 

When it is time to cut a release, we can add automation that completes all the steps for us. That is, a workflow which:

1) Moves anything in `unreleased` to the new package version in the changelog
2) Update the package.json with the new version
3) Publishes the new version to npm registry & publishes a git tag to the repo

**Comment by kv979w** [comment]
@finn-orsini Using semantic-release doesn't necessarily lead to this scenario:
> publishing a new release for every change results in unecessary churn for our consumers

It's configurable, but by default commits tagged with maintenance tags like "chore" or "ci" won't publish a new release or update the package.json version. I understand there could be concerns about accidentally publishing releases or a lack of control on release timelines.
