### ISSUE TITLE
Remove non-production necessary files from release

### ISSUE THREAD

**Issue by draco2003** [wayfair/git-parse#54]
## Description
Should we provide a cleaner/smaller release file? 

## What's the benefit of this feature?
Reduce size of release. Don't send files that aren't used by the npm package itself. 

## Possible Implementation (optional)
Seems like there are actions available to help with this if we don't want to do it ourselves. 
Example (not endorsing, just providing as example)
https://github.com/shashkovdanil/clean-publish

**Comment by kv979w** [comment]
👍  Another way would be set up an npmignore file: https://npm.github.io/publishing-pkgs-docs/publishing/the-npmignore-file.html

**Comment by kv979w** [comment]
Turns out the --copy-files parameter in the babel CLI here https://github.com/wayfair/git-parse/blob/0032eb40b4b4237afc3c180d7f66672c6a3e8228/scripts/compile-src.js#L15 is causing the __tests__ folder to be included in the distribution.
