### ISSUE TITLE
Rename paths with spaces not recognized correctly

### ISSUE THREAD

**Issue by flash1293** [wayfair/git-parse#73]
## What happens?
In case of a PR renaming a file with spaces in the path, the old and new path of the change entry will be broken. Maybe similar to https://github.com/wayfair/git-parse/issues/63

## What were you expecting to happen?

Should recognize them correctly

## Reproducing the Bug

Check out https://github.com/vuejs/docs
Try to parse commit bb9f97a9ca0acc7408e0c59750e712d94360f499

The diff via `git show` in the terminal:
```
diff --git a/src/.vuepress/public/images/sponsors/primevue copy.png b/src/public/images/sponsors/primevue copy.png
similarity index 100%
rename from src/.vuepress/public/images/sponsors/primevue copy.png
rename to src/public/images/sponsors/primevue copy.png
```

The diff entry via git-parse:
```
{
      "oldPath": "src/.vuepress/public/images/sponsors/primevue copy.png\tsrc/public/images/sponsors/primevue",
      "newPath": "copy.png"
    }
```

## Environment

3.0.0 on MacOs

**Comment by finn-orsini** [comment]
👋 Thanks for filing this issue!

So far I have been unable to reproduce the bug as described by cloning the vue docs and running: 

```js
gitToJs("../docs", {
	sinceCommit: "bb9f97a9ca0acc7408e0c59750e712d94360f499",
});
```

Can you please provide more specifics about how to recreate this issue? A minimal reproduction repo & script would be really helpful to track this down.
